// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Noxy.NET.Test.Persistence;

#nullable disable

namespace Noxy.NET.Test.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Authentication.TableAuthentication", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("TimeCreated");

                    b.ToTable("TableAuthentication");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Authentication.TableIdentity", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeSignIn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.HasKey("ID");

                    b.HasIndex("TimeCreated");

                    b.HasIndex("UserID");

                    b.ToTable("TableIdentity");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Authentication.TableUser", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthenticationID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeSignIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeVerified")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("AuthenticationID")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TimeCreated");

                    b.ToTable("TableUser");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Data.Discriminators.TableDataProperty", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElementID")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaIdentifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ElementID");

                    b.HasIndex("TimeCreated");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Data.TableDataElement", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaIdentifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("TimeCreated");

                    b.ToTable("TableDataElement");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Data.TableDataSystemParameter", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaIdentifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeApproved")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeEffective")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("TimeCreated");

                    b.ToTable("TableDataSystemParameter");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Data.TableDataTextParameter", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaIdentifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeApproved")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeEffective")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("TimeCreated");

                    b.ToTable("TableDataTextParameter");

                    b.HasData(
                        new
                        {
                            ID = new Guid("019764ca-25c4-7785-bd02-ebdc5a27fb39"),
                            SchemaIdentifier = "ButtonActivate",
                            TimeApproved = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeEffective = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "Activate"
                        },
                        new
                        {
                            ID = new Guid("019764ca-25c4-7785-bd02-efa276b57b62"),
                            SchemaIdentifier = "ButtonCreate",
                            TimeApproved = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeEffective = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "Create"
                        },
                        new
                        {
                            ID = new Guid("019764ca-25c4-7785-bd02-f1e439a3bb07"),
                            SchemaIdentifier = "ButtonUpdate",
                            TimeApproved = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeEffective = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "Update"
                        },
                        new
                        {
                            ID = new Guid("019764ca-25c4-7785-bd02-f7c5260cb82d"),
                            SchemaIdentifier = "ButtonSubmit",
                            TimeApproved = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeEffective = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "Submit"
                        },
                        new
                        {
                            ID = new Guid("01977fb8-8d9e-7179-b098-d37940c4d817"),
                            SchemaIdentifier = "ButtonSignIn",
                            TimeApproved = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeEffective = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "Sign in"
                        },
                        new
                        {
                            ID = new Guid("01977fb8-8d9e-7179-b098-d431e095ba95"),
                            SchemaIdentifier = "ButtonSignUp",
                            TimeApproved = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeEffective = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "Sign up"
                        },
                        new
                        {
                            ID = new Guid("01978309-3029-74e9-931c-436de21f95b0"),
                            SchemaIdentifier = "LinkNavigationSchema",
                            TimeApproved = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeEffective = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "Schemas"
                        });
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableAssociationSchemaActionInputHasAttribute", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RelationID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("EntityID");

                    b.HasIndex("RelationID");

                    b.HasIndex("TimeCreated");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableSchemaDynamicValue", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SchemaID")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaIdentifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("SchemaID");

                    b.HasIndex("TimeCreated");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableSchemaProperty", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SchemaID")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaIdentifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("SchemaID");

                    b.HasIndex("TimeCreated");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Junctions.TableJunctionSchemaActionHasActionStep", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RelationID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("RelationID");

                    b.HasIndex("TimeCreated");

                    b.HasIndex("EntityID", "RelationID")
                        .IsUnique();

                    b.ToTable("TableJunctionSchemaActionHasActionStep");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Junctions.TableJunctionSchemaActionHasDynamicValueCode", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RelationID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("RelationID");

                    b.HasIndex("TimeCreated");

                    b.HasIndex("EntityID", "RelationID")
                        .IsUnique();

                    b.ToTable("TableJunctionSchemaActionHasDynamicValueCode");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Junctions.TableJunctionSchemaActionStepHasActionInput", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RelationID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("RelationID");

                    b.HasIndex("TimeCreated");

                    b.HasIndex("EntityID", "RelationID")
                        .IsUnique();

                    b.ToTable("TableJunctionSchemaActionStepHasActionInput");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Junctions.TableJunctionSchemaContextHasAction", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RelationID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("RelationID");

                    b.HasIndex("TimeCreated");

                    b.HasIndex("EntityID", "RelationID")
                        .IsUnique();

                    b.ToTable("TableJunctionSchemaContextHasAction");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Junctions.TableJunctionSchemaContextHasElement", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RelationID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("RelationID");

                    b.HasIndex("TimeCreated");

                    b.HasIndex("EntityID", "RelationID")
                        .IsUnique();

                    b.ToTable("TableJunctionSchemaContextHasElement");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Junctions.TableJunctionSchemaElementHasProperty", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RelationID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("RelationID");

                    b.HasIndex("TimeCreated");

                    b.HasIndex("EntityID", "RelationID")
                        .IsUnique();

                    b.ToTable("TableJunctionSchemaElementHasProperty");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Junctions.TableJunctionSchemaInputHasAttribute", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RelationID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("RelationID");

                    b.HasIndex("TimeCreated");

                    b.HasIndex("EntityID", "RelationID")
                        .IsUnique();

                    b.ToTable("TableJunctionSchemaInputHasAttribute");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchema", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TimeActivated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("TimeCreated");

                    b.ToTable("TableSchema");

                    b.HasData(
                        new
                        {
                            ID = new Guid("01974e8c-ecb8-75ab-9070-ef902ff370a7"),
                            IsActive = true,
                            Name = "Base schema",
                            Note = "This is a base schema intended to be cloned and extended.",
                            Order = 1,
                            TimeActivated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaAction", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SchemaID")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaIdentifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TitleDynamicID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("TimeCreated");

                    b.HasIndex("TitleDynamicID");

                    b.HasIndex("SchemaID", "SchemaIdentifier")
                        .IsUnique();

                    b.ToTable("TableSchemaAction");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaActionInput", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InputID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SchemaID")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaIdentifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("InputID");

                    b.HasIndex("TimeCreated");

                    b.HasIndex("SchemaID", "SchemaIdentifier")
                        .IsUnique();

                    b.ToTable("TableSchemaActionInput");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaActionStep", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SchemaID")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaIdentifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("TimeCreated");

                    b.HasIndex("SchemaID", "SchemaIdentifier")
                        .IsUnique();

                    b.ToTable("TableSchemaActionStep");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaAttribute", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsList")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SchemaID")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaIdentifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("TimeCreated");

                    b.HasIndex("SchemaID", "SchemaIdentifier")
                        .IsUnique();

                    b.ToTable("TableSchemaAttribute");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaContext", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SchemaID")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaIdentifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("TimeCreated");

                    b.HasIndex("SchemaID", "SchemaIdentifier")
                        .IsUnique();

                    b.ToTable("TableSchemaContext");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaElement", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SchemaID")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaIdentifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("TimeCreated");

                    b.HasIndex("SchemaID", "SchemaIdentifier")
                        .IsUnique();

                    b.ToTable("TableSchemaElement");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaGroupElement", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SchemaID")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaIdentifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("TimeCreated");

                    b.HasIndex("SchemaID", "SchemaIdentifier")
                        .IsUnique();

                    b.ToTable("TableSchemaGroupElement");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaInput", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SchemaID")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaIdentifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("TimeCreated");

                    b.HasIndex("SchemaID", "SchemaIdentifier")
                        .IsUnique();

                    b.ToTable("TableSchemaInput");

                    b.HasData(
                        new
                        {
                            ID = new Guid("01974e8c-ecb8-75ab-9070-f0fed39b9c54"),
                            Name = "Checkbox",
                            Note = "The base checkbox input type.",
                            Order = 1,
                            SchemaID = new Guid("01974e8c-ecb8-75ab-9070-ef902ff370a7"),
                            SchemaIdentifier = "ActionInputCheckbox",
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ID = new Guid("01974e8c-ecb8-75ab-9070-f625218aed76"),
                            Name = "Date input",
                            Note = "The base date input type.",
                            Order = 2,
                            SchemaID = new Guid("01974e8c-ecb8-75ab-9070-ef902ff370a7"),
                            SchemaIdentifier = "ActionInputDate",
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ID = new Guid("019765f7-2847-757d-8d6f-e48dbec5bbeb"),
                            Name = "Decimal input",
                            Note = "The base decimal input type.",
                            Order = 3,
                            SchemaID = new Guid("01974e8c-ecb8-75ab-9070-ef902ff370a7"),
                            SchemaIdentifier = "ActionInputDecimal",
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ID = new Guid("019765f7-2847-757d-8d6f-ea72d6453f86"),
                            Name = "Integer input",
                            Note = "The base integer input type.",
                            Order = 4,
                            SchemaID = new Guid("01974e8c-ecb8-75ab-9070-ef902ff370a7"),
                            SchemaIdentifier = "ActionInputInteger",
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ID = new Guid("019765f7-2847-757d-8d6f-ec49fff67113"),
                            Name = "Password input",
                            Note = "The base password input type.",
                            Order = 5,
                            SchemaID = new Guid("01974e8c-ecb8-75ab-9070-ef902ff370a7"),
                            SchemaIdentifier = "ActionInputPassword",
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ID = new Guid("019765f7-2847-757d-8d6f-ec49fff67fa1"),
                            Name = "Single choice input",
                            Note = "The base single choice input type.",
                            Order = 6,
                            SchemaID = new Guid("01974e8c-ecb8-75ab-9070-ef902ff370a7"),
                            SchemaIdentifier = "ActionInputSingleChoice",
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ID = new Guid("01974e8c-ecb8-75ab-9070-f8a855e17dda"),
                            Name = "Text input",
                            Note = "The base text input type.",
                            Order = 7,
                            SchemaID = new Guid("01974e8c-ecb8-75ab-9070-ef902ff370a7"),
                            SchemaIdentifier = "ActionInputText",
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TableSchemaElementTableSchemaGroupElement", b =>
                {
                    b.Property<Guid>("ElementListID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupElementListID")
                        .HasColumnType("TEXT");

                    b.HasKey("ElementListID", "GroupElementListID");

                    b.HasIndex("GroupElementListID");

                    b.ToTable("TableSchemaElementTableSchemaGroupElement");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Data.TableDataPropertyBoolean", b =>
                {
                    b.HasBaseType("Noxy.NET.Test.Persistence.Tables.Data.Discriminators.TableDataProperty");

                    b.Property<bool?>("Value")
                        .HasColumnType("INTEGER");

                    b.ToTable("TableDataPropertyBoolean");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Data.TableDataPropertyDateTime", b =>
                {
                    b.HasBaseType("Noxy.NET.Test.Persistence.Tables.Data.Discriminators.TableDataProperty");

                    b.Property<DateTime?>("Value")
                        .HasColumnType("TEXT");

                    b.ToTable("TableDataPropertyDateTime");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Data.TableDataPropertyString", b =>
                {
                    b.HasBaseType("Noxy.NET.Test.Persistence.Tables.Data.Discriminators.TableDataProperty");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.ToTable("TableDataPropertyString");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Associations.TableAssociationSchemaActionInputHasAttributeDynamicValue", b =>
                {
                    b.HasBaseType("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableAssociationSchemaActionInputHasAttribute");

                    b.Property<Guid>("ValueID")
                        .HasColumnType("TEXT");

                    b.HasIndex("ValueID");

                    b.ToTable("TableAssociationSchemaActionInputHasAttributeDynamicValue");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Associations.TableAssociationSchemaActionInputHasAttributeInteger", b =>
                {
                    b.HasBaseType("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableAssociationSchemaActionInputHasAttribute");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.ToTable("TableAssociationSchemaActionInputHasAttributeInteger");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Associations.TableAssociationSchemaActionInputHasAttributeString", b =>
                {
                    b.HasBaseType("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableAssociationSchemaActionInputHasAttribute");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("TableAssociationSchemaActionInputHasAttributeString");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaDynamicValueCode", b =>
                {
                    b.HasBaseType("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableSchemaDynamicValue");

                    b.Property<bool>("IsAsynchronous")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("SchemaID", "SchemaIdentifier")
                        .IsUnique();

                    b.ToTable("TableSchemaDynamicValueCode");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaDynamicValueSystemParameter", b =>
                {
                    b.HasBaseType("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableSchemaDynamicValue");

                    b.Property<bool>("IsApprovalRequired")
                        .HasColumnType("INTEGER");

                    b.HasIndex("SchemaID", "SchemaIdentifier")
                        .IsUnique();

                    b.ToTable("TableSchemaDynamicValueSystemParameter");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaDynamicValueTextParameter", b =>
                {
                    b.HasBaseType("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableSchemaDynamicValue");

                    b.Property<bool>("IsApprovalRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasIndex("SchemaID", "SchemaIdentifier")
                        .IsUnique();

                    b.ToTable("TableSchemaDynamicValueTextParameter");

                    b.HasData(
                        new
                        {
                            ID = new Guid("019764ca-25c4-7785-bd02-daa168ae477d"),
                            Name = "ButtonActivate",
                            Note = "",
                            Order = 1,
                            SchemaID = new Guid("01974e8c-ecb8-75ab-9070-ef902ff370a7"),
                            SchemaIdentifier = "ButtonActivate",
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApprovalRequired = false,
                            Type = 0
                        },
                        new
                        {
                            ID = new Guid("019764ca-25c4-7785-bd02-de67a804e592"),
                            Name = "ButtonCreate",
                            Note = "",
                            Order = 2,
                            SchemaID = new Guid("01974e8c-ecb8-75ab-9070-ef902ff370a7"),
                            SchemaIdentifier = "ButtonCreate",
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApprovalRequired = false,
                            Type = 0
                        },
                        new
                        {
                            ID = new Guid("019764ca-25c4-7785-bd02-e26550fa3aa9"),
                            Name = "ButtonUpdate",
                            Note = "",
                            Order = 3,
                            SchemaID = new Guid("01974e8c-ecb8-75ab-9070-ef902ff370a7"),
                            SchemaIdentifier = "ButtonUpdate",
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApprovalRequired = false,
                            Type = 0
                        },
                        new
                        {
                            ID = new Guid("019764ca-25c4-7785-bd02-e5902e766443"),
                            Name = "ButtonSubmit",
                            Note = "",
                            Order = 4,
                            SchemaID = new Guid("01974e8c-ecb8-75ab-9070-ef902ff370a7"),
                            SchemaIdentifier = "ButtonSubmit",
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApprovalRequired = false,
                            Type = 0
                        },
                        new
                        {
                            ID = new Guid("01977fb8-8d9e-7179-b098-d8800c456351"),
                            Name = "ButtonSignIn",
                            Note = "",
                            Order = 5,
                            SchemaID = new Guid("01974e8c-ecb8-75ab-9070-ef902ff370a7"),
                            SchemaIdentifier = "ButtonSignIn",
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApprovalRequired = false,
                            Type = 0
                        },
                        new
                        {
                            ID = new Guid("01977fb8-8d9e-7179-b098-dde7fae42dc4"),
                            Name = "ButtonSignUp",
                            Note = "",
                            Order = 6,
                            SchemaID = new Guid("01974e8c-ecb8-75ab-9070-ef902ff370a7"),
                            SchemaIdentifier = "ButtonSignUp",
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApprovalRequired = false,
                            Type = 0
                        },
                        new
                        {
                            ID = new Guid("01978309-3029-74e9-931c-3cf1322948fd"),
                            Name = "LinkNavigationSchema",
                            Note = "",
                            Order = 7,
                            SchemaID = new Guid("01974e8c-ecb8-75ab-9070-ef902ff370a7"),
                            SchemaIdentifier = "LinkNavigationSchema",
                            TimeCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsApprovalRequired = false,
                            Type = 0
                        });
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaPropertyBoolean", b =>
                {
                    b.HasBaseType("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableSchemaProperty");

                    b.HasIndex("SchemaID", "SchemaIdentifier")
                        .IsUnique();

                    b.ToTable("TableSchemaPropertyBoolean");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaPropertyDateTime", b =>
                {
                    b.HasBaseType("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableSchemaProperty");

                    b.HasIndex("SchemaID", "SchemaIdentifier")
                        .IsUnique();

                    b.ToTable("TableSchemaPropertyDateTime");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaPropertyString", b =>
                {
                    b.HasBaseType("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableSchemaProperty");

                    b.HasIndex("SchemaID", "SchemaIdentifier")
                        .IsUnique();

                    b.ToTable("TableSchemaPropertyString");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Authentication.TableIdentity", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Authentication.TableUser", "User")
                        .WithMany("IdentityList")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Authentication.TableUser", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Authentication.TableAuthentication", "Authentication")
                        .WithOne("User")
                        .HasForeignKey("Noxy.NET.Test.Persistence.Tables.Authentication.TableUser", "AuthenticationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authentication");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Data.Discriminators.TableDataProperty", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Data.TableDataElement", "Element")
                        .WithMany("PropertyList")
                        .HasForeignKey("ElementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableAssociationSchemaActionInputHasAttribute", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaActionInput", "Entity")
                        .WithMany("AttributeList")
                        .HasForeignKey("EntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaAttribute", "Relation")
                        .WithMany()
                        .HasForeignKey("RelationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableSchemaDynamicValue", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchema", "Schema")
                        .WithMany("DynamicValueList")
                        .HasForeignKey("SchemaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableSchemaProperty", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchema", "Schema")
                        .WithMany("PropertyList")
                        .HasForeignKey("SchemaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Junctions.TableJunctionSchemaActionHasActionStep", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaAction", "Entity")
                        .WithMany("ActionStepList")
                        .HasForeignKey("EntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaActionStep", "Relation")
                        .WithMany("ActionList")
                        .HasForeignKey("RelationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Junctions.TableJunctionSchemaActionHasDynamicValueCode", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaAction", "Entity")
                        .WithMany("DynamicValueCodeList")
                        .HasForeignKey("EntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaDynamicValueCode", "Relation")
                        .WithMany()
                        .HasForeignKey("RelationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Junctions.TableJunctionSchemaActionStepHasActionInput", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaActionStep", "Entity")
                        .WithMany("ActionInputList")
                        .HasForeignKey("EntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaActionInput", "Relation")
                        .WithMany("ActionStepList")
                        .HasForeignKey("RelationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Junctions.TableJunctionSchemaContextHasAction", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaContext", "Entity")
                        .WithMany("ActionList")
                        .HasForeignKey("EntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaAction", "Relation")
                        .WithMany("ContextList")
                        .HasForeignKey("RelationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Junctions.TableJunctionSchemaContextHasElement", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaContext", "Entity")
                        .WithMany("ElementList")
                        .HasForeignKey("EntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaElement", "Relation")
                        .WithMany("ContextList")
                        .HasForeignKey("RelationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Junctions.TableJunctionSchemaElementHasProperty", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaElement", "Entity")
                        .WithMany("PropertyList")
                        .HasForeignKey("EntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableSchemaProperty", "Relation")
                        .WithMany("ElementList")
                        .HasForeignKey("RelationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Junctions.TableJunctionSchemaInputHasAttribute", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaInput", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaAttribute", "Relation")
                        .WithMany("InputList")
                        .HasForeignKey("RelationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaAction", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchema", "Schema")
                        .WithMany("ActionList")
                        .HasForeignKey("SchemaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableSchemaDynamicValue", "TitleDynamic")
                        .WithMany("ActionList")
                        .HasForeignKey("TitleDynamicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schema");

                    b.Navigation("TitleDynamic");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaActionInput", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaInput", "Input")
                        .WithMany("ActionInputList")
                        .HasForeignKey("InputID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchema", "Schema")
                        .WithMany("ActionInputList")
                        .HasForeignKey("SchemaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Input");

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaActionStep", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchema", "Schema")
                        .WithMany("ActionStepList")
                        .HasForeignKey("SchemaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaAttribute", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchema", "Schema")
                        .WithMany()
                        .HasForeignKey("SchemaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaContext", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchema", "Schema")
                        .WithMany("ContextList")
                        .HasForeignKey("SchemaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaElement", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchema", "Schema")
                        .WithMany("ElementList")
                        .HasForeignKey("SchemaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaGroupElement", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchema", "Schema")
                        .WithMany("GroupElementList")
                        .HasForeignKey("SchemaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaInput", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchema", "Schema")
                        .WithMany("InputList")
                        .HasForeignKey("SchemaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("TableSchemaElementTableSchemaGroupElement", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaElement", null)
                        .WithMany()
                        .HasForeignKey("ElementListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaGroupElement", null)
                        .WithMany()
                        .HasForeignKey("GroupElementListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Associations.TableAssociationSchemaActionInputHasAttributeDynamicValue", b =>
                {
                    b.HasOne("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableSchemaDynamicValue", "Value")
                        .WithMany("ActionInputAttributeList")
                        .HasForeignKey("ValueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Value");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Authentication.TableAuthentication", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Authentication.TableUser", b =>
                {
                    b.Navigation("IdentityList");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Data.TableDataElement", b =>
                {
                    b.Navigation("PropertyList");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableSchemaDynamicValue", b =>
                {
                    b.Navigation("ActionInputAttributeList");

                    b.Navigation("ActionList");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.Discriminators.TableSchemaProperty", b =>
                {
                    b.Navigation("ElementList");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchema", b =>
                {
                    b.Navigation("ActionInputList");

                    b.Navigation("ActionList");

                    b.Navigation("ActionStepList");

                    b.Navigation("ContextList");

                    b.Navigation("DynamicValueList");

                    b.Navigation("ElementList");

                    b.Navigation("GroupElementList");

                    b.Navigation("InputList");

                    b.Navigation("PropertyList");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaAction", b =>
                {
                    b.Navigation("ActionStepList");

                    b.Navigation("ContextList");

                    b.Navigation("DynamicValueCodeList");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaActionInput", b =>
                {
                    b.Navigation("ActionStepList");

                    b.Navigation("AttributeList");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaActionStep", b =>
                {
                    b.Navigation("ActionInputList");

                    b.Navigation("ActionList");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaAttribute", b =>
                {
                    b.Navigation("InputList");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaContext", b =>
                {
                    b.Navigation("ActionList");

                    b.Navigation("ElementList");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaElement", b =>
                {
                    b.Navigation("ContextList");

                    b.Navigation("PropertyList");
                });

            modelBuilder.Entity("Noxy.NET.Test.Persistence.Tables.Schemas.TableSchemaInput", b =>
                {
                    b.Navigation("ActionInputList");
                });
#pragma warning restore 612, 618
        }
    }
}
